### ISSUE TITLE
Canvas does not display in Pop! OS (Linux, Debian)

### ISSUE THREAD

**Issue by Fulguritude** [martinRenou/ipycanvas#137]
The same notebook which works fine on a Mac (Firefox) does not work on a Linux machine (also Firefox). I've downloaded all the dependencies (checked with `pip3 check`), have npm and ipycanvas installed globally, etc. The canvas (and multicanvas) simply do not display on my platform. ipywidgets do display fine, though

**Comment by martinRenou** [comment]
Is it Jupyter Notebook or JupyterLab?

**Comment by Fulguritude** [comment]
Jupyter Notebook

`jupyter notebook` gives

```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.17.0
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```

**Comment by martinRenou** [comment]
Can you run `jupyter nbextension list`?

**Comment by martinRenou** [comment]
Can you also run `which jupyter` as well

**Comment by Fulguritude** [comment]
result: ` /usr/bin/jupyter`

**Comment by martinRenou** [comment]
The nbextension seems to not be installed. You can try running `jupyter nbextension install --py --sys-prefix ipycanvas`. This should not be have been needed though.

Let me suggest to use `conda` environments or other tools for making virtual environments. You will have less installation problems. Installing in the root folder is not a good idea, especially if you use `pip`, which does not do any version compatibility checking, it can break everything.

**Comment by Fulguritude** [comment]
I tried your command. It gives me a "Module not found" error

```log
$> sudo jupyter nbextension install --py --sys-prefix ipycanvas
Traceback (most recent call last):
  File "/usr/bin/jupyter-nbextension", line 11, in <module>
    load_entry_point('notebook==6.0.3', 'console_scripts', 'jupyter-nbextension')()
  File "/usr/lib/python3/dist-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 983, in start
    super(NBExtensionApp, self).start()
  File "/usr/lib/python3/dist-packages/jupyter_core/application.py", line 259, in start
    self.subapp.start()
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 711, in start
    self.install_extensions()
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 682, in install_extensions
    full_dests = install(self.extra_args[0],
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 206, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 1117, in _get_nbextension_metadata
    m = import_item(module)
  File "/usr/lib/python3/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'ipycanvas'
```

I use pip3 as a global installer to have all I need everywhere on my machine (never had any problem with it), but I'll follow your advice and try things out with conda. Thanks

**Comment by martinRenou** [comment]
Can you run `which pip3`?

How did you install ipycanvas in the first place?

**Comment by Fulguritude** [comment]
I had done a simple `sudo pip3 install ipycanvas`...

```
$> which pip3
/usr/bin/pip3
```

```
$> pip3 list
Package                 Version
----------------------- -------------
attrs                   19.3.0
backcall                0.2.0
bleach                  3.2.1
blinker                 1.4
Brlapi                  0.7.0
certifi                 2020.6.20
chardet                 3.0.4
chrome-gnome-shell      0.0.0
click                   7.1.2
colorama                0.4.3
command-not-found       0.3
cryptography            3.0
cupshelpers             1.0
cycler                  0.10.0
dbus-python             1.2.16
decorator               4.4.2
defer                   1.0.6
defusedxml              0.6.0
distro                  1.5.0
distro-info             0.23ubuntu1
entrypoints             0.3
gyp                     0.1
hidpidaemon             18.4.6
html5lib                1.1
httplib2                0.18.1
idna                    2.10
importlib-metadata      1.6.0
ipycanvas               0.6.0
ipykernel               5.3.4
ipython                 7.17.0
ipython-genutils        0.2.0
ipywidgets              7.5.1
jedi                    0.17.0
jeepney                 0.4.3
Jinja2                  2.11.2
joblib                  0.17.0
jsonschema              3.2.0
jupyter-client          6.1.6
jupyter-console         6.1.0
jupyter-core            4.6.3
kernelstub              3.1.4
keyring                 21.3.0
kiwisolver              1.2.0
language-selector       0.1
launchpadlib            1.10.13
lazr.restfulclient      0.14.2
lazr.uri                1.0.5
louis                   3.14.0
macaroonbakery          1.3.1
MarkupSafe              1.1.1
matplotlib              3.3.2
mistune                 0.8.4
more-itertools          4.2.0
nbconvert               5.6.1
nbformat                5.0.7
netifaces               0.10.4
notebook                6.0.3
numpy                   1.19.3
oauthlib                3.1.0
packaging               20.4
pandas                  1.1.4
pandocfilters           1.4.2
parso                   0.7.0
pbr                     5.5.1
pexpect                 4.6.0
pickleshare             0.7.5
Pillow                  8.0.1
pip                     20.1.1
pop-transition          1.0.1
prometheus-client       0.7.1
prompt-toolkit          3.0.6
protobuf                3.12.3
pycairo                 1.16.2
pycups                  2.0.1
pydbus                  0.6.0
pyflatpak               0.4.0
Pygments                2.3.1
PyGObject               3.38.0
PyJWT                   1.7.1
pymacaroons             0.13.0
PyNaCl                  1.4.0
pyparsing               2.4.7
pyRFC3339               1.1
pyrsistent              0.15.5
python-apt              2.1.3+ubuntu1
python-dateutil         2.8.1
python-debian           0.1.37
python-xlib             0.27
pytz                    2020.1
pyxdg                   0.26
PyYAML                  5.3.1
pyzmq                   19.0.2
repolib                 1.5.0
repoman                 1.2.2
requests                2.23.0
requests-unixsocket     0.2.0
scikit-learn            0.23.2
scipy                   1.5.3
screen-resolution-extra 0.0.0
seaborn                 0.11.0
SecretStorage           3.1.2
Send2Trash              1.5.0
sessioninstaller        0.0.0
setuptools              49.3.1
simplejson              3.17.0
six                     1.15.0
sklearn                 0.0
systemd-python          234
terminado               0.8.2
testpath                0.4.4
testresources           2.0.1
threadpoolctl           2.1.0
tornado                 6.0.4
traitlets               4.3.3
ubuntu-advantage-tools  24.4
ubuntu-drivers-common   0.0.0
ufw                     0.36
urllib3                 1.25.9
wadllib                 1.3.4
wcwidth                 0.1.9
webencodings            0.5.1
wheel                   0.34.2
widgetsnbextension      3.5.1
xkit                    0.0.0
zipp                    1.0.0
```

**Comment by Fulguritude** [comment]
Installed conda, but the package ipycanvas is not found

```
$> conda install ipycanvas
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ipycanvas

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by martinRenou** [comment]
It's in the conda-forge channel, so you need to do `conda install -c conda-forge ipycanvas`.

> I had done a simple sudo pip3 install ipycanvas

The problem might have been that you installed it with `sudo`.

**Comment by Fulguritude** [comment]
I tried uninstalling ipycanvas, then reinstalling it without sudo: it didn't work. However, for good measure, I uninstalled and reinstalled all dependencies for my notebook without sudo, then did the same but with sudo. It worked when reinstalling everything with sudo ! I suppose the issue was that I had installed somethings with sudo and some things without, which is odd. As to why this affected ipycanvas when it seems to only have ipywidgets as a dependency, I do not know. Maybe it has something to do with my nodejs install ? Idk

Thanks a lot for your help in any case, and sorry for taking up your time !
Thanks also for your work on ipycanvas; both my students and I greatly profit from its existence :)

**Comment by martinRenou** [comment]
Sorry I could not help you more. I don't want to be too pushy, but you should really use miniconda, your life will be much easier :) 

> both my students and I greatly profit from its existence :)

That's great to hear! I'd be happy to see what you do with it

**Comment by Fulguritude** [comment]
When I get the chance to put my notebooks into opensource, I'll let you know :)

**Comment by martinRenou** [comment]
Thanks!
