### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by ionox0** [martinRenou/ipycanvas#328]
![Screen Shot 2023-04-05 at 11 58 10 AM](https://user-images.githubusercontent.com/6385646/230137156-9bdb0422-121e-4745-a3c2-cc82f4555788.png)

I am using poetry as a package manager, and have the following versions of packages installed:

```
  • Updating jupyterlab-widgets (3.0.7 -> 1.1.2)
  • Updating widgetsnbextension (3.1.4 -> 3.6.2)
  • Updating ipywidgets (7.1.2 -> 7.7.3)
  • Updating pillow (9.4.0 -> 9.5.0)
  • Updating ipycanvas (0.9.0 -> 0.13.1)
```

**Comment by ionox0** [comment]
I see the following errors in the console:

```
index.es6.js:288 Plugin 'ipycanvas:plugin' failed to activate.
(anonymous) @ index.es6.js:288
index.es6.js:289 Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    at e.resolveRequiredService (index.es6.js:201:35)
    at index.es6.js:156:70
    at Array.map (<anonymous>)
    at e.activatePlugin (index.es6.js:156:38)
    at index.es6.js:287:26
    at Array.map (<anonymous>)
    at e.start (index.es6.js:286:33)
    at G (index.out.js:625:7)
(anonymous) @ index.es6.js:289
272.d8d5a83bf0ac99d2aad5.js:1 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early
(anonymous) @ 272.d8d5a83bf0ac99d2aad5.js:1
523.45ece939ba0b134aa71f.js:1 Error: widget model not found
    at x.get_model (523.45ece939ba0b134aa71f.js:1:6292)
    at u.renderModel (523.45ece939ba0b134aa71f.js:1:972)
renderModel @ 523.45ece939ba0b134aa71f.js:1
272.d8d5a83bf0ac99d2aad5.js:1 Could not instantiate widget
(anonymous) @ 272.d8d5a83bf0ac99d2aad5.js:1
272.d8d5a83bf0ac99d2aad5.js:1 Error: Could not create a model.
    at 272.d8d5a83bf0ac99d2aad5.js:1:2205
    at async _handleCommOpen (523.45ece939ba0b134aa71f.js:1:2798)
    at async b._handleCommOpen (default.js:1094:102)
    at async b._handleMessage (default.js:1262:43)
(anonymous) @ 272.d8d5a83bf0ac99d2aad5.js:1
default.js:1101 Exception opening new comm
_handleCommOpen @ default.js:1101
2523.45ece939ba0b134aa71f.js:1 Uncaught (in promise) Error: Module ipycanvas, semver range ^0.13 is not registered as a widget module
    at x.loadClass (523.45ece939ba0b134aa71f.js:1:5727)
    at x.<anonymous> (272.d8d5a83bf0ac99d2aad5.js:1:9479)
    at 272.d8d5a83bf0ac99d2aad5.js:1:6081
    at Object.next (272.d8d5a83bf0ac99d2aad5.js:1:6186)
    at 272.d8d5a83bf0ac99d2aad5.js:1:5122
    at new Promise (<anonymous>)
    at D (272.d8d5a83bf0ac99d2aad5.js:1:4867)
    at e._make_model (272.d8d5a83bf0ac99d2aad5.js:1:9358)
    at x.<anonymous> (272.d8d5a83bf0ac99d2aad5.js:1:9212)
    at 272.d8d5a83bf0ac99d2aad5.js:1:6081
272.d8d5a83bf0ac99d2aad5.js:1 Could not instantiate widget
(anonymous) @ 272.d8d5a83bf0ac99d2aad5.js:1
272.d8d5a83bf0ac99d2aad5.js:1 Error: Could not create a model.
    at 272.d8d5a83bf0ac99d2aad5.js:1:2205
    at async _handleCommOpen (523.45ece939ba0b134aa71f.js:1:2798)
    at async b._handleCommOpen (default.js:1094:102)
    at async b._handleMessage (default.js:1262:43)
(anonymous) @ 272.d8d5a83bf0ac99d2aad5.js:1
default.js:1101 Exception opening new comm
_handleCommOpen @ default.js:1101
2523.45ece939ba0b134aa71f.js:1 Uncaught (in promise) Error: Module ipycanvas, semver range ^0.13 is not registered as a widget module
    at x.loadClass (523.45ece939ba0b134aa71f.js:1:5727)
    at x.<anonymous> (272.d8d5a83bf0ac99d2aad5.js:1:9479)
    at 272.d8d5a83bf0ac99d2aad5.js:1:6081
    at Object.next (272.d8d5a83bf0ac99d2aad5.js:1:6186)
    at 272.d8d5a83bf0ac99d2aad5.js:1:5122
    at new Promise (<anonymous>)
    at D (272.d8d5a83bf0ac99d2aad5.js:1:4867)
    at e._make_model (272.d8d5a83bf0ac99d2aad5.js:1:9358)
    at x.<anonymous> (272.d8d5a83bf0ac99d2aad5.js:1:9212)
    at 272.d8d5a83bf0ac99d2aad5.js:1:6081
523.45ece939ba0b134aa71f.js:1 Error: Module ipycanvas, semver range ^0.13 is not registered as a widget module
    at x.loadClass (523.45ece939ba0b134aa71f.js:1:5727)
    at x.<anonymous> (272.d8d5a83bf0ac99d2aad5.js:1:9479)
    at 272.d8d5a83bf0ac99d2aad5.js:1:6081
    at Object.next (272.d8d5a83bf0ac99d2aad5.js:1:6186)
    at 272.d8d5a83bf0ac99d2aad5.js:1:5122
    at new Promise (<anonymous>)
    at D (272.d8d5a83bf0ac99d2aad5.js:1:4867)
    at e._make_model (272.d8d5a83bf0ac99d2aad5.js:1:9358)
    at x.<anonymous> (272.d8d5a83bf0ac99d2aad5.js:1:9212)
    at 272.d8d5a83bf0ac99d2aad5.js:1:6081
renderModel @ 523.45ece939ba0b134aa71f.js:1
```
